app [target] {
	fuzz: platform "https://github.com/lukewilliamboswell/roc-fuzz/releases/download/0.2.1/9Qpttb6LTgcMaVsSBLsnaiS2mDUrf6Bxa6dX9Rqwviz4.tar.zst",
	pdf: "../package/all.roc",
}

import fuzz.Fuzz
import NavigationTargets

## Nearly every generated field is a small code chosen from a boundary pool
## rather than a free value, because the navigation surface is defined by
## boundaries: a destination name is rejected at one byte over the limit, an
## outline depth at one level over, a label range at a start page that fails to
## ascend. Uniform values would spend the whole campaign rediscovering that a
## random string is not a valid URI and would never land on a limit. The two
## free strings remain, as the last choice in every pool, so the fuzzer can
## still reach a form the pools did not anticipate.
##
## `bulk` reaches the two count limits without paying for them in entropy: an
## outline of 4097 entries or a label list of 1025 ranges is generated by
## repetition, so the count check is reachable from one byte instead of from
## thousands.
##
## Field order is load-bearing. The generator consumes fuzzer bytes field by
## field and a field the input never reaches decodes as zero, while libFuzzer
## starts at a length limit of a handful of bytes and raises it only once
## coverage stops growing. An earlier arrangement of this record put the
## generated strings first and measurably starved everything behind them: every
## retained input decoded with the fault selector at zero and both navigation
## lists empty. The fields are therefore ordered by how much of the navigation
## surface they reach per byte - the fault selector, the bulk selector, then the
## two navigation lists, and the string-carrying content last.
Input := {
	arm : U8,
	bulk : U8,
	labels : List({ page_code : U8, prefix : U8, start_number : U64, style : U8 }),
	outline : List({ depth_code : U8, destination : U8, open : U8, title : U8 }),
	sections : List({ kind : U8, name : U8, uri : U8, words : Str }),
	text : Str,
}.{
	generator_for : Fuzz.FuzzEncoding -> Fuzz.Generator(Input)
	generator_for = |_| {
		{
			arm: Fuzz.u8_in(0, 34),
			bulk: Fuzz.u8_in(0, 15),
			labels: Fuzz.list(
				{
					page_code: Fuzz.u8,
					prefix: Fuzz.u8,
					start_number: Fuzz.u64_in(0, 3),
					style: Fuzz.u8,
				}.Fuzz,
				6,
			),
			outline: Fuzz.list(
				{
					depth_code: Fuzz.u8,
					destination: Fuzz.u8,
					open: Fuzz.u8,
					title: Fuzz.u8,
				}.Fuzz,
				8,
			),
			sections: Fuzz.list(
				{
					kind: Fuzz.u8,
					name: Fuzz.u8,
					uri: Fuzz.u8,
					words: Fuzz.str,
				}.Fuzz,
				8,
			),
			text: Fuzz.str,
		}.Fuzz
	}
}

## The two properties are kept apart so a crash names which one broke: the
## free-form document proves only repeatability and transactional rejection,
## while the single-fault table is the one entitled to name a variant.
test : Input -> Fuzz.Outcome
test = |Input.(input)| {
	if !NavigationTargets.deterministic_navigation(input) {
		crash "authored navigation was not a deterministic, transactional function of the document"
	}
	if !NavigationTargets.single_fault(input.arm) {
		crash "a single injected navigation fault produced the wrong typed rejection"
	}
	Fuzz.keep
}

target = Fuzz.target({
	name: "roc-pdf-navigation-property",
	test,
	show: |input| Str.inspect(input),
})
