import pdf.Color
import pdf.Document
import pdf.Layout
import pdf.Pdf
import pdf.Theme

ThemeTargets :: [].{
	Block : { items : List(Str), kind : U8, level : U8, text : Str }
	Input : {
		blocks : List(Block),
		body_leading : U8,
		body_size : U8,
		bullet_indent : U8,
		heading_leading : U8,
		heading_size : U8,
		margin_bottom : U8,
		margin_left : U8,
		margin_right : U8,
		margin_top : U8,
		page_size : U8,
		paragraph_spacing : U8,
		profile : U8,
		title : Str,
		title_leading : U8,
		title_size : U8,
	}

	## Drive the unvalidated public `Theme` surface into pagination.
	##
	## `with_body_style`, `with_heading_style`, `with_title_style`,
	## `with_page_margin`, `with_paragraph_spacing`, and `with_bullet_indent`
	## all accept a raw `I64` `Layout.Unit` and perform no validation of their
	## own, so a caller can hand the paginator a zero or negative leading, a
	## margin pair wider than the page, or a size near `I64` saturation. Those
	## are exactly the shapes that make a layout loop fail to advance or an
	## accumulator wrap, so the enduring output contracts are checked against
	## the whole ladder of magnitudes rather than against plausible themes:
	##
	## - the run terminates at all, for every combination,
	## - identical explicit inputs produce identical bytes (core invariant 12),
	## - the buffered and chunked encoders agree byte for byte because they
	##   drive one emission transition over one sealed plan,
	## - and a theme the pipeline rejects is rejected the same way every time,
	##   through both entrypoints, with no partial file emitted.
	##
	## A typed rejection is an ordinary outcome here. The property is that the
	## outcome is stable and reachable, never that an extreme theme succeeds.
	theme_output : Input -> Bool
	theme_output = |input| {
		document = Pdf.document({
			contents: input.blocks.map(block_for),
			language: "en-AU",
			title: input.title,
		})
		options = options_for(input)

		match (Pdf.to_bytes_with(document, options), Pdf.to_bytes_with(document, options)) {

			## Transactional failure is an ordinary outcome, but it must repeat
			## and it must agree across both entrypoints.
			(Err(_), Err(_)) => match Pdf.to_chunks_with(document, options) {
				Err(_) => True
				Ok(_) => False
			}
			(Ok(first), Ok(second)) => {
				if first != second {
					return False
				}
				drained(document, options) == Some(first)
			}
			_ => False
		}
	}
}

## A ladder of interesting layout magnitudes: zero, degenerate negatives, the
## ordinary point sizes a real theme uses, a page-sized value, and magnitudes
## far enough out that any unchecked addition of two of them would wrap `I64`.
## The choice is taken modulo the ladder length so every generated byte lands
## on a documented rung rather than on an arbitrary nearby integer.
unit_for : U8 -> Layout.Unit
unit_for = |choice| Layout.Unit.from_raw(
	match choice % 16 {
		0 => 0
		1 => 1
		2 => -1
		3 => -72000
		4 => 1000
		5 => 8000
		6 => 11000
		7 => 14000
		8 => 18000
		9 => 24000
		10 => 72000
		11 => 595276
		12 => 1000000000
		13 => -1000000000
		14 => 4611686018427387904
		_ => -4611686018427387904
	},
)

## Every theme knob the public surface exposes is varied at once. Varying them
## one at a time would miss the interesting cases, which are pairs: a leading
## smaller than a size, or a left and right margin that together exceed the
## page width.
options_for : ThemeTargets.Input -> Pdf.Options
options_for = |input| {
	black = Color.srgb8({ blue: 0, green: 0, red: 0 })
	face = Theme.body_font(Theme.default)
	styled = Theme.with_title_style(
		Theme.with_heading_style(
			Theme.with_body_style(
				Theme.default,
				{ color: black, font: face, leading: unit_for(input.body_leading), size: unit_for(input.body_size) },
			),
			{ color: black, font: face, leading: unit_for(input.heading_leading), size: unit_for(input.heading_size) },
		),
		{ color: black, font: face, leading: unit_for(input.title_leading), size: unit_for(input.title_size) },
	)
	spaced = Theme.with_bullet_indent(
		Theme.with_paragraph_spacing(
			Theme.with_page_margin(
				styled,
				{
					bottom: unit_for(input.margin_bottom),
					left: unit_for(input.margin_left),
					right: unit_for(input.margin_right),
					top: unit_for(input.margin_top),
				},
			),
			unit_for(input.paragraph_spacing),
		),
		unit_for(input.bullet_indent),
	)

	base = Pdf.Options.with_theme(Pdf.Options.default, spaced)
	sized = if input.page_size % 2 == 0 {
		Pdf.Options.with_page_size(base, A4)
	} else {
		Pdf.Options.with_page_size(base, Letter)
	}

	## Archive and AccessibleArchive are still unavailable capabilities, so two
	## of the three profiles reject before layout runs. They are generated
	## anyway: the contract that an unavailable profile is a stable typed
	## rejection rather than a crash is worth holding under extreme themes too.
	match input.profile % 3 {
		0 => Pdf.Options.with_profile(sized, Standard)
		1 => Pdf.Options.with_profile(sized, Archive)
		_ => Pdf.Options.with_profile(sized, AccessibleArchive)
	}
}

## Sealing already succeeded for the buffered path, so a chunked failure here is
## a disagreement between two entrypoints over one sealed plan.
drained : Document, Pdf.Options -> [None, Some(List(U8))]
drained = |document, options| match Pdf.to_chunks_with(document, options) {
	Err(_) => None
	Ok(encoder) => Some(drain(encoder))
}

drain : Pdf.Encode -> List(U8)
drain = |encoder| {
	var $encoder = encoder
	var $bytes = []
	var $done = False
	while $done == False {
		match Pdf.next_chunk($encoder) {
			Done => {
				$done = True
			}
			Emit(chunk, next) => {
				$bytes = append_all($bytes, chunk)
				$encoder = next
			}
		}
	}
	$bytes
}

block_for : ThemeTargets.Block -> Document.Block
block_for = |block| match block.kind % 4 {
	0 => Pdf.title(block.text)
	1 => Pdf.heading(block.level % 6 + 1, block.text)
	2 => Pdf.paragraph(block.text)
	_ => Pdf.bullets(block.items)
}

append_all : List(a), List(a) -> List(a)
append_all = |left, right| {
	var $result = left
	var $index = 0
	while $index < right.len() {
		$result = $result.append(list_at(right, $index))
		$index = $index + 1
	}
	$result
}

list_at : List(a), U64 -> a
list_at = |items, index| match items.get(index) {
	Err(OutOfBounds) => crash "fuzz property escaped a validated dense index"
	Ok(value) => value
}

## Enough authored content to force wrapping and pagination decisions; a single
## short paragraph would settle on one line whatever the theme said.
sample_blocks : List(ThemeTargets.Block)
sample_blocks = [
	{ items: [], kind: 0, level: 0, text: "Extreme theme" },
	{ items: [], kind: 1, level: 2, text: "A heading that is long enough to wrap" },
	{ items: [], kind: 2, level: 0, text: "Body text long enough that the paginator has to make more than one line-breaking decision about it." },
	{ items: ["first bullet", "second bullet"], kind: 3, level: 0, text: "" },
]

## An ordinary theme in ladder terms: 14pt leading over 11pt body, 18/15 for
## headings, 28-ish leading over 24pt titles, and 72pt margins.
ordinary_input : ThemeTargets.Input
ordinary_input = {
	blocks: sample_blocks,
	body_leading: 7,
	body_size: 6,
	bullet_indent: 8,
	heading_leading: 8,
	heading_size: 9,
	margin_bottom: 10,
	margin_left: 10,
	margin_right: 10,
	margin_top: 10,
	page_size: 0,
	paragraph_spacing: 5,
	profile: 0,
	title: "Extreme theme",
	title_leading: 9,
	title_size: 9,
}

## The ordinary theme is the control: whatever the extremes below do, the
## everyday case still satisfies the same contracts.
expect ThemeTargets.theme_output(ordinary_input)

## Zero leading on every style. A paginator that advances by leading cannot
## make progress on a zero step, so this is the shape that either terminates
## with a typed rejection or does not terminate at all.
expect ThemeTargets.theme_output({ ..ordinary_input, body_leading: 0, heading_leading: 0, title_leading: 0 })

## Negative margins on all four sides, which place the text frame outside the
## media box. Nothing in the public surface prevents this, so it must still
## resolve to one stable outcome.
expect ThemeTargets.theme_output({ ..ordinary_input, margin_bottom: 3, margin_left: 3, margin_right: 3, margin_top: 3 })

## Sizes and leadings near `I64` saturation in both directions, mixed so that
## adding a size to a leading, or a top margin to a bottom margin, would wrap
## if either sum were unchecked.
expect ThemeTargets.theme_output({
	..ordinary_input,
	body_leading: 14,
	body_size: 15,
	bullet_indent: 14,
	margin_bottom: 15,
	margin_top: 14,
	paragraph_spacing: 15,
	title_leading: 15,
	title_size: 14,
})
