#!/usr/bin/env python3
from __future__ import annotations

import argparse
import hashlib
import os
import tempfile
from pathlib import Path

from fontTools import subset
from fontTools.ttLib import TTFont


ROOT = Path(__file__).resolve().parents[1]
SOURCE = ROOT / "vendor" / "fonts" / "Inter-4.1-Regular.ttf"
OUTPUT = ROOT / "vendor" / "fonts" / "RocPdfSans-Regular.ttf"
MODULE_OUTPUT = ROOT / "package" / "KernelBuiltInFont.roc"
SOURCE_SHA256 = "40d692fce188e4471e2b3cba937be967878f631ad3ebbbdcd587687c7ebe0c82"
FONTTOOLS_VERSION = "4.61.1"

# The built-in facade declares this exact coverage policy. Advanced callers
# supply separately validated faces for other scripts and ranges.
UNICODE_RANGES = (
    (0x0020, 0x007E),
    (0x00A0, 0x017F),
    (0x0300, 0x036F),
    (0x2000, 0x206F),
    (0x20AC, 0x20AC),
    (0x2122, 0x2122),
    (0x2190, 0x2193),
    (0x2212, 0x2212),
)


def sha256(path: Path) -> str:
    return hashlib.sha256(path.read_bytes()).hexdigest()


def selected_scalars() -> set[int]:
    return {
        scalar
        for first, last in UNICODE_RANGES
        for scalar in range(first, last + 1)
    }


def rename_font(font: TTFont) -> None:
    replacements = {
        1: "Roc PDF Sans",
        2: "Regular",
        3: "RocPdfSans-Regular-1.0",
        4: "Roc PDF Sans Regular",
        6: "RocPdfSans-Regular",
        16: "Roc PDF Sans",
        17: "Regular",
    }
    names = font["name"]
    for record in names.names:
        replacement = replacements.get(record.nameID)
        if replacement is not None:
            record.string = replacement.encode(record.getEncoding())


def module_source(font_bytes: bytes) -> str:
    values = "\n".join(f"\t\t{value}," for value in font_bytes)
    return (
        "## Generated by scripts/build_builtin_font.py from the audited built-in font.\n"
        "## It is source data so roc bundle retains the package-private byte import.\n"
        "KernelBuiltInFont :: [].{\n"
        "\tbytes : List(U8)\n"
        "\tbytes = [\n"
        f"{values}\n"
        "\t]\n"
        "}\n"
    )


def write_module(output: Path, font_bytes: bytes) -> None:
    output.parent.mkdir(parents=True, exist_ok=True)
    output.write_text(module_source(font_bytes), encoding="utf-8", newline="\n")


def build(output: Path, module_output: Path | None = None) -> None:
    if sha256(SOURCE) != SOURCE_SHA256:
        raise SystemExit(f"unexpected Inter source digest: {sha256(SOURCE)}")

    import fontTools

    if fontTools.__version__ != FONTTOOLS_VERSION:
        raise SystemExit(
            f"fontTools {FONTTOOLS_VERSION} is required, got {fontTools.__version__}"
        )

    options = subset.Options()
    options.layout_features = ["*"]
    options.name_IDs = [0, 1, 2, 3, 4, 5, 6, 13, 14, 16, 17]
    options.name_languages = [0x0409]
    options.notdef_glyph = True
    options.notdef_outline = True
    options.recommended_glyphs = True
    options.recalc_timestamp = False
    options.canonical_order = True

    font = TTFont(SOURCE, recalcTimestamp=False, lazy=False)
    worker = subset.Subsetter(options=options)
    worker.populate(unicodes=selected_scalars())
    worker.subset(font)
    rename_font(font)

    output.parent.mkdir(parents=True, exist_ok=True)
    fd, temporary_name = tempfile.mkstemp(prefix="RocPdfSans-", suffix=".ttf", dir=output.parent)
    os.close(fd)
    temporary = Path(temporary_name)
    try:
        font.save(temporary, reorderTables=True)
        temporary.replace(output)
    finally:
        temporary.unlink(missing_ok=True)
    if module_output is not None:
        write_module(module_output, output.read_bytes())


def main() -> None:
    parser = argparse.ArgumentParser()
    parser.add_argument(
        "--check",
        action="store_true",
        help="Regenerate to a temporary file and compare it with the retained asset.",
    )
    args = parser.parse_args()

    if args.check:
        with tempfile.TemporaryDirectory(prefix="roc-pdf-font-") as directory:
            candidate = Path(directory) / OUTPUT.name
            candidate_module = Path(directory) / MODULE_OUTPUT.name
            build(candidate, candidate_module)
            if not OUTPUT.exists() or candidate.read_bytes() != OUTPUT.read_bytes():
                raise SystemExit(f"{OUTPUT} is not the deterministic generated font")
            if not MODULE_OUTPUT.exists() or candidate_module.read_bytes() != MODULE_OUTPUT.read_bytes():
                raise SystemExit(f"{MODULE_OUTPUT} is not the deterministic generated font module")
        print(f"PASS built-in font {sha256(OUTPUT)}")
    else:
        build(OUTPUT, MODULE_OUTPUT)
        print(f"Wrote {OUTPUT} ({OUTPUT.stat().st_size} bytes, sha256={sha256(OUTPUT)})")


if __name__ == "__main__":
    main()
