#!/usr/bin/env python3
"""Emit the package-private sRGB profile module from the pinned ICC asset.

The vendored `vendor/icc/sRGB2014.icc` is the International Color Consortium's
official sRGB v2 profile (see `vendor/icc/NOTICE.md` for its provenance and
license). This script verifies the asset against its pinned digest and the ICC
header facts, then emits `package/KernelSrgbProfile.roc` so the packaged sRGB
profile is compiled pure Roc package data with its tag directory and identity
digest available to the color pipeline and its tests.
"""

from __future__ import annotations

import argparse
import hashlib
import tempfile
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
SOURCE = ROOT / "vendor" / "icc" / "sRGB2014.icc"
MODULE_OUTPUT = ROOT / "package" / "KernelSrgbProfile.roc"
SOURCE_SHA256 = "384b832de3412066743b52a75ee906b6fb9fb8d9e09e936fc2c43223815c6e0a"


def sha256(payload: bytes) -> str:
    return hashlib.sha256(payload).hexdigest()


def read_u32(payload: bytes, offset: int) -> int:
    return int.from_bytes(payload[offset : offset + 4], "big")


def verify_profile(payload: bytes) -> list[tuple[int, int, int]]:
    if sha256(payload) != SOURCE_SHA256:
        raise SystemExit(f"unexpected sRGB2014.icc digest: {sha256(payload)}")
    if read_u32(payload, 0) != len(payload):
        raise SystemExit("sRGB2014.icc declared size does not match its bytes")
    if read_u32(payload, 36) != 0x61637370:
        raise SystemExit("sRGB2014.icc is missing the 'acsp' signature")
    if payload[8] != 2:
        raise SystemExit("sRGB2014.icc is not an ICC v2 profile")
    if read_u32(payload, 16) != 0x52474220:
        raise SystemExit("sRGB2014.icc is not an RGB device profile")

    # ISO 15076-1 profile ID: MD5 over the profile with the flags, rendering
    # intent, and profile ID header fields zeroed.
    zeroed = bytearray(payload)
    zeroed[44:48] = b"\0\0\0\0"
    zeroed[64:68] = b"\0\0\0\0"
    zeroed[84:100] = b"\0" * 16
    if hashlib.md5(bytes(zeroed)).digest() != payload[84:100]:
        raise SystemExit("sRGB2014.icc embedded profile ID does not verify")

    count = read_u32(payload, 128)
    if 132 + count * 12 > len(payload):
        raise SystemExit("sRGB2014.icc tag table escapes the profile")
    tags: list[tuple[int, int, int]] = []
    for index in range(count):
        record = 132 + index * 12
        signature = read_u32(payload, record)
        offset = read_u32(payload, record + 4)
        length = read_u32(payload, record + 8)
        if offset > len(payload) or length > len(payload) - offset:
            raise SystemExit(f"sRGB2014.icc tag {index} escapes the profile")
        tags.append((signature, offset, length))
    return tags


def module_source(payload: bytes, tags: list[tuple[int, int, int]]) -> str:
    digest_values = ", ".join(str(value) for value in hashlib.sha256(payload).digest())
    tag_lines = "\n".join(
        f"\t\t{{ bytes: Semantics.Range.from_start_and_length({offset}, {length}),"
        f" signature: Color.TagSignature.from_raw({signature}) }},"
        for signature, offset, length in tags
    )
    byte_values = "\n".join(f"\t\t{value}," for value in payload)
    return (
        "## Generated by scripts/build_srgb_profile.py from the pinned ICC asset\n"
        "## vendor/icc/sRGB2014.icc. It is source data so roc bundle retains the\n"
        "## package-private byte import; provenance and license live in\n"
        "## vendor/icc/NOTICE.md.\n"
        "import Color\n"
        "import KernelColor\n"
        "import KernelSha256\n"
        "import Semantics\n"
        "\n"
        "KernelSrgbProfile :: [].{\n"
        "\n"
        "\t## SHA-256 of `bytes`, pinned to the same digest as the provenance\n"
        "\t## manifest entry for the vendored asset.\n"
        "\tsha256 : List(U8)\n"
        f"\tsha256 = [{digest_values}]\n"
        "\n"
        "\tbyte_count : U64\n"
        f"\tbyte_count = {len(payload)}\n"
        "\n"
        f"\ttag_count : U64\n"
        f"\ttag_count = {len(tags)}\n"
        "\n"
        "\t## The profile's tag directory as validated records in table order,\n"
        "\t## with ranges into `bytes`.\n"
        "\ttags : List(Color.IccTag)\n"
        "\ttags = [\n"
        f"{tag_lines}\n"
        "\t]\n"
        "\n"
        "\t## A profile record for one dense profile slot whose tag records\n"
        "\t## occupy `tag_start ..` in the caller's flat tag store.\n"
        "\tprofile : U64, U64 -> Color.IccProfile\n"
        "\tprofile = |index, tag_start| {\n"
        "\t\tbytes,\n"
        "\t\tcomponents: Three,\n"
        "\t\tid: Color.ProfileId.from_index(index),\n"
        "\t\ttags: Semantics.Range.from_start_and_length(tag_start, tag_count),\n"
        "\t\tversion: IccV2,\n"
        "\t}\n"
        "\n"
        "\tbytes : List(U8)\n"
        "\tbytes = [\n"
        f"{byte_values}\n"
        "\t]\n"
        "}\n"
        "\n"
        "## The packaged profile carries its pinned identity digest and length.\n"
        "expect match KernelSha256.digest(KernelSrgbProfile.bytes) {\n"
        "\tErr(_) => Bool.False\n"
        "\tOk(digest) => digest == KernelSrgbProfile.sha256 and KernelSrgbProfile.bytes.len() == KernelSrgbProfile.byte_count\n"
        "}\n"
        "\n"
        "## The packaged profile passes the ICC inspection boundary as sRGB.\n"
        "expect {\n"
        "\tstore : Color.Store\n"
        "\tstore = {\n"
        "\t\tprofiles: [KernelSrgbProfile.profile(0, 0)],\n"
        "\t\tspaces: [{ id: Color.SpaceId.from_index(0), space: Srgb(Color.ProfileId.from_index(0)) }],\n"
        "\t\ttags: KernelSrgbProfile.tags,\n"
        "\t}\n"
        "\tlimits = KernelColor.Limits.make({\n"
        "\t\tmax_icc_bytes: KernelSrgbProfile.byte_count,\n"
        "\t\tmax_profiles: 1,\n"
        "\t\tmax_spaces: 1,\n"
        "\t\tmax_tags: KernelSrgbProfile.tag_count,\n"
        "\t})\n"
        "\tmatch KernelColor.Plan.build(store, limits) {\n"
        "\t\tErr(_) => Bool.False\n"
        "\t\tOk(plan) => KernelColor.Plan.components(plan, Color.SpaceId.from_index(0)) == Three\n"
        "\t}\n"
        "}\n"
    )


def build(module_output: Path) -> None:
    payload = SOURCE.read_bytes()
    tags = verify_profile(payload)
    module_output.write_text(module_source(payload, tags), encoding="utf-8", newline="\n")


def main() -> None:
    parser = argparse.ArgumentParser()
    parser.add_argument(
        "--check",
        action="store_true",
        help="Regenerate to a temporary file and compare it with the retained module.",
    )
    args = parser.parse_args()

    if args.check:
        with tempfile.TemporaryDirectory(prefix="roc-pdf-icc-") as directory:
            candidate = Path(directory) / MODULE_OUTPUT.name
            build(candidate)
            if not MODULE_OUTPUT.exists() or candidate.read_bytes() != MODULE_OUTPUT.read_bytes():
                raise SystemExit(f"{MODULE_OUTPUT} is not the deterministic generated profile module")
        print(f"PASS packaged sRGB profile {SOURCE_SHA256}")
    else:
        build(MODULE_OUTPUT)
        print(f"Wrote {MODULE_OUTPUT} ({MODULE_OUTPUT.stat().st_size} bytes)")


if __name__ == "__main__":
    main()
