## Generated by scripts/build_srgb_profile.py from the pinned ICC asset
## package/sRGB2014.icc, which it byte-imports at compile time;
## provenance and license live in vendor/icc/NOTICE.md.
import "sRGB2014.icc" as profile_bytes : List(U8)
import Color
import KernelColor
import KernelSha256
import Semantics

KernelSrgbProfile :: [].{

	## SHA-256 of `bytes`, pinned to the same digest as the provenance
	## manifest entry for the vendored asset.
	sha256 : List(U8)
	sha256 = [56, 75, 131, 45, 227, 65, 32, 102, 116, 59, 82, 167, 94, 233, 6, 182, 251, 159, 184, 217, 224, 158, 147, 111, 194, 196, 50, 35, 129, 92, 110, 10]

	byte_count : U64
	byte_count = 3024

	tag_count : U64
	tag_count = 16

	## The profile's tag directory as validated records in table order,
	## with ranges into `bytes`.
	tags : List(Color.IccTag)
	tags = [
		{ bytes: Semantics.Range.from_start_and_length(324, 99), signature: Color.TagSignature.from_raw(1684370275) },
		{ bytes: Semantics.Range.from_start_and_length(424, 20), signature: Color.TagSignature.from_raw(1649957210) },
		{ bytes: Semantics.Range.from_start_and_length(444, 2060), signature: Color.TagSignature.from_raw(1649693251) },
		{ bytes: Semantics.Range.from_start_and_length(444, 2060), signature: Color.TagSignature.from_raw(1733579331) },
		{ bytes: Semantics.Range.from_start_and_length(444, 2060), signature: Color.TagSignature.from_raw(1918128707) },
		{ bytes: Semantics.Range.from_start_and_length(2504, 136), signature: Color.TagSignature.from_raw(1684890724) },
		{ bytes: Semantics.Range.from_start_and_length(2640, 20), signature: Color.TagSignature.from_raw(1733843290) },
		{ bytes: Semantics.Range.from_start_and_length(2660, 20), signature: Color.TagSignature.from_raw(1819635049) },
		{ bytes: Semantics.Range.from_start_and_length(2680, 36), signature: Color.TagSignature.from_raw(1835360627) },
		{ bytes: Semantics.Range.from_start_and_length(2716, 20), signature: Color.TagSignature.from_raw(1651208308) },
		{ bytes: Semantics.Range.from_start_and_length(2736, 20), signature: Color.TagSignature.from_raw(1918392666) },
		{ bytes: Semantics.Range.from_start_and_length(2756, 12), signature: Color.TagSignature.from_raw(1952801640) },
		{ bytes: Semantics.Range.from_start_and_length(2768, 135), signature: Color.TagSignature.from_raw(1987405156) },
		{ bytes: Semantics.Range.from_start_and_length(2904, 20), signature: Color.TagSignature.from_raw(2004119668) },
		{ bytes: Semantics.Range.from_start_and_length(2924, 55), signature: Color.TagSignature.from_raw(1668313716) },
		{ bytes: Semantics.Range.from_start_and_length(2980, 44), signature: Color.TagSignature.from_raw(1667785060) },
	]

	## A profile record for one dense profile slot whose tag records
	## occupy `tag_start ..` in the caller's flat tag store.
	profile : U64, U64 -> Color.IccProfile
	profile = |index, tag_start| {
		bytes,
		components: Three,
		id: Color.ProfileId.from_index(index),
		tags: Semantics.Range.from_start_and_length(tag_start, tag_count),
		version: IccV2,
	}

	bytes : List(U8)
	bytes = profile_bytes
}

## The packaged profile carries its pinned identity digest and length.
expect match KernelSha256.digest(KernelSrgbProfile.bytes) {
	Err(_) => Bool.False
	Ok(digest) => digest == KernelSrgbProfile.sha256 and KernelSrgbProfile.bytes.len() == KernelSrgbProfile.byte_count
}

## The packaged profile passes the ICC inspection boundary as sRGB.
expect {
	store : Color.Store
	store = {
		profiles: [KernelSrgbProfile.profile(0, 0)],
		spaces: [{ id: Color.SpaceId.from_index(0), space: Srgb(Color.ProfileId.from_index(0)) }],
		tags: KernelSrgbProfile.tags,
	}
	limits = KernelColor.Limits.make({
		max_icc_bytes: KernelSrgbProfile.byte_count,
		max_profiles: 1,
		max_spaces: 1,
		max_tags: KernelSrgbProfile.tag_count,
	})
	match KernelColor.Plan.build(store, limits) {
		Err(_) => Bool.False
		Ok(plan) => KernelColor.Plan.components(plan, Color.SpaceId.from_index(0)) == Three
	}
}
