package
	[
		Pdf,
		Document,
		Semantics,
		Layout,
		Scene,
		Text,
		Font,
		Image,
		Color,
		Metadata,
		Encode,
		Conformance,
		Theme,
	]
	{
		deflate: "https://github.com/niclas-ahden/roc-deflate/releases/download/0.1.0/9d7QRzf6vgYMDqXgTsL5sTh8B475yeL8KUAp8TJKs2Q5.tar.zst",
	}
