name: Nightly configuration
on:
  pull_request:
  workflow_dispatch:
permissions:
  contents: read
jobs:
  configuration:
    uses: lukewilliamboswell/roc-automation/.github/workflows/check-config.yml@20b09cca5b8e68d1a0e56f633e74890840c47f08
